version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
    open-pull-requests-limit: 10
    target-branch: master
    reviewers:
      - ckittl
      - johanneshiry
      - t-ober
      - sensarmad
    ignore:
      - dependency-name: org.jgrapht:jgrapht-core
        versions:
          - ">= 1.5.a, < 1.6"