version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
    open-pull-requests-limit: 10
    target-branch: main
    ignore:
      - dependency-name: org.jgrapht:jgrapht-core
        versions:
          - ">= 1.5.a, < 1.6"
      - dependency-name: org.scalatest:scalatest_2.13
        versions:
          - "3.3.0-SNAP+"
