@startuml

(*) --> "Choose all closed switches"
--> "Identify switch groups"
note right: By iterating over all existing switches\nand building bags of connected nodes.\nIf a node of a following switch is already\nin a bag, then add the switch to this\nswitch group.
--> "Take the next switch group"
--> "Identify main node"
note left: By counting the occurrences of\nthis node within all nodes of\nthat switch group. If all nodes\noccur only once, take the first\none.
--> "Build collapsing mapping"
note left: By assigning all nodes\nof a switch group to the\nmain node.
if "Last group" then
    -->[true] "Consider mapping when converting node models"
    --> "Do not convert switch models"
    --> (*)
else
    -->[false] "Take the next switch group"

@enduml